{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(569, 30) (569,)\n",
      "Target classes: ['malignant' 'benign']\n"
     ]
    }
   ],
   "source": [
    "from sklearn.datasets import load_breast_cancer\n",
    "import numpy as np\n",
    "from typing import Tuple, Union, List\n",
    "\n",
    "random_state = 88844\n",
    "rng = np.random.default_rng(seed=random_state)\n",
    "\n",
    "data = load_breast_cancer()\n",
    "X, y = data[\"data\"], data[\"target\"]\n",
    "feature_names = data[\"feature_names\"]\n",
    "target_names = data[\"target_names\"]\n",
    "\n",
    "print(X.shape, y.shape)\n",
    "print(\"Target classes:\", target_names)\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Baseline model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "X_train size: (455, 30)\n",
      "X_test size: (114, 30)\n",
      "              precision    recall  f1-score   support\n",
      "\n",
      "           0       0.98      0.96      0.97        45\n",
      "           1       0.97      0.99      0.98        69\n",
      "\n",
      "    accuracy                           0.97       114\n",
      "   macro avg       0.97      0.97      0.97       114\n",
      "weighted avg       0.97      0.97      0.97       114\n",
      "\n"
     ]
    }
   ],
   "source": [
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.pipeline import make_pipeline\n",
    "from sklearn.metrics import classification_report\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(\n",
    "    X, y, test_size=0.2, random_state=random_state\n",
    ")\n",
    "print(f\"X_train size: {X_train.shape}\")\n",
    "print(f\"X_test size: {X_test.shape}\")\n",
    "\n",
    "pipe = make_pipeline(StandardScaler(), LogisticRegression())\n",
    "\n",
    "pipe.fit(X_train, y_train)\n",
    "\n",
    "y_test_preds = pipe.predict(X_test)\n",
    "print(classification_report(y_test, y_test_preds))\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Implementing the same model using `flower`"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Ingredients:\n",
    "1. Split the data into $n$ datasets, each representing a different location where the data lives\n",
    "2. Define functions for:\n",
    "    - Getting model parameters\n",
    "    - Setting model parameters\n",
    "3. Define `FlowerClient` \n",
    "    - Should contain the following:\n",
    "        - `get_parameters`\n",
    "        - `fit`\n",
    "        - `evaluate`\n",
    "4. Set Federated learning strategy\n",
    "6. Simulate!"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Data setup\n",
    "Since we have ~450 training instances, let's say we have $n=5$ different hospitals where the breast cancer data lives"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "((91, 30), (91,))"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def split_dataset(\n",
    "    X: np.array, y: np.array, n_clients: int = 5\n",
    ") -> List[Tuple[np.array, np.array]]:\n",
    "    n_clients = 5\n",
    "    partition_sizes = len(X) // n_clients\n",
    "\n",
    "    partition_indices = rng.choice(\n",
    "        len(X), size=(n_clients, partition_sizes), replace=False\n",
    "    )\n",
    "    sets = [(X[pidx], y[pidx]) for pidx in partition_indices]\n",
    "    return sets\n",
    "\n",
    "\n",
    "train_sets = split_dataset(X_train, y_train)\n",
    "train_sets[0][0].shape, train_sets[0][1].shape  # Number of samples for our first client\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "We'll have a single test set shared across all clients"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "test_set = (X_test, y_test)"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Fetching/reloading model parameters\n",
    "Taken from the `flower` [sklearn example](https://github.com/adap/flower/blob/main/examples/sklearn-logreg-mnist/utils.py)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "metadata": {},
   "outputs": [],
   "source": [
    "# XY = Tuple[np.ndarray, np.ndarray]\n",
    "# LogRegParams = Union[XY, Tuple[np.ndarray]]\n",
    "\n",
    "\n",
    "# def get_model_parameters(model: LogisticRegression) -> LogRegParams:\n",
    "#     \"\"\"Returns the paramters of a sklearn LogisticRegression model.\"\"\"\n",
    "#     if model.fit_intercept:\n",
    "#         params = [\n",
    "#             model.coef_,\n",
    "#             model.intercept_,\n",
    "#         ]\n",
    "#     else:\n",
    "#         params = [\n",
    "#             model.coef_,\n",
    "#         ]\n",
    "#     return params\n",
    "\n",
    "\n",
    "# def set_model_params(\n",
    "#     model: LogisticRegression, params: LogRegParams\n",
    "# ) -> LogisticRegression:\n",
    "#     \"\"\"Sets the parameters of a sklean LogisticRegression model.\"\"\"\n",
    "#     model.coef_ = params[0]\n",
    "#     if model.fit_intercept:\n",
    "#         model.intercept_ = params[1]\n",
    "#     return model\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 88,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.pipeline import Pipeline\n",
    "\n",
    "def get_model_parameters(model: Pipeline) -> dict:\n",
    "    params = {\n",
    "        \"scaler\": [pipe[0].scale_, pipe[0].mean_, pipe[0].var_],\n",
    "        \"clf\": [pipe[1].coef_]\n",
    "    }\n",
    "        \n",
    "    if pipe[1].fit_intercept:\n",
    "        params[\"clf\"].append(pipe[1].intercept_)\n",
    "\n",
    "    return params\n",
    "\n",
    "\n",
    "def set_model_params(pipe: Pipeline, params) -> Pipeline:\n",
    "    \"\"\"Since we're working wiht a pipeline object, we need to set\n",
    "    the parameters for all underlying models. In this case a scaler and LogisticRegression.\n",
    "    \"\"\"\n",
    "    pipe[0].scale_ = params[\"scaler\"][0]\n",
    "    pipe[0].mean_ = params[\"scaler\"][1]\n",
    "    pipe[0].var_ = params[\"scaler\"][2]\n",
    "\n",
    "    pipe[1].coef_ = params[\"clf\"][0]\n",
    "    if pipe[1].fit_intercept:\n",
    "        pipe[1].intercept_ = params[\"clf\"][1]\n",
    "    return pipe\n",
    "\n",
    "\n",
    "def set_initial_params(pipe: Pipeline, n_feats) -> Pipeline:\n",
    "    pipe[0].scale_ = np.zeros(shape=(n_feats))\n",
    "    pipe[0].mean_ = np.zeros(shape=(n_feats))\n",
    "    pipe[0].var_ = np.zeros(shape=(n_feats))\n",
    "\n",
    "    pipe[1].coef_ = np.zeros(shape=(n_feats))\n",
    "    if pipe[1].fit_intercept:\n",
    "        pipe[1].intercept_ = np.zeros(shape=(n_feats))\n",
    "    return pipe\n",
    "    pipe[1]"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Define FlowerClient"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 87,
   "metadata": {},
   "outputs": [],
   "source": [
    "import warnings\n",
    "import flwr as fl\n",
    "from sklearn.metrics import log_loss\n",
    "\n",
    "class BreastCancerClient(fl.client.NumPyClient):\n",
    "    def __init__(self, pipe, train_set, test_set):\n",
    "        self.pipe = pipe\n",
    "        self.clf = self.pipe.steps[-1][0]\n",
    "        self.X_train, self.y_train = train_set\n",
    "        self.X_test, self.y_test = test_set\n",
    "\n",
    "    def get_parameters(self, config):\n",
    "        return get_model_parameters(self.pipe)\n",
    "\n",
    "    def fit(self, parameters, config):\n",
    "        set_model_params(self.pipe, parameters)\n",
    "        with warnings.catch_warnings():\n",
    "            warnings.simplefilter(\"ignore\")\n",
    "            self.pip.fit(self.X_train, self.y_train)\n",
    "\n",
    "        print(f\"Training finished for round {config['server_round']}\")\n",
    "        return get_model_parameters(self.pipe), len(self.X_train), {}\n",
    "\n",
    "    def evaluate(self, parameters, config):  # type: ignore\n",
    "        set_model_params(self.pipe, parameters)\n",
    "        loss = log_loss(self.y_test, self.clf.predict_proba(self.X_test))\n",
    "        accuracy = self.clf.score(self.X_test, self.y_test)\n",
    "        return loss, len(self.X_test), {\"accuracy\": accuracy}\n",
    "\n",
    "def launch_client(client_id, train_sets=train_sets, test_set=test_set):\n",
    "    model = make_pipeline(StandardScaler(), LogisticRegression(max_iter=1, warm_start=True))\n",
    "    train_set = train_sets[int(client_id)]\n",
    "    set_initial_params(model, n_feats=(train_set[0][0].shape[-1])) \n",
    "    return BreastCancerClient(model, train_set, test_set)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 82,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "30"
      ]
     },
     "execution_count": 82,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "train_sets[0][0].shape[-1]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 94,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(30,)"
      ]
     },
     "execution_count": 94,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "launch_client(2).pipe[1].coef_.shape"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Set Federated learning strategy\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "strategy = fl.server.strategy.FedAvg(\n",
    "    fraction_fit=1.0,  # Sample 100% of available clients for training\n",
    "    fraction_evaluate=0.5,  # Sample 50% of available clients for evaluation\n",
    "    min_fit_clients=5,\n",
    "    min_evaluate_clients=1,  # Never sample less than 5 clients for evaluation\n",
    "    min_available_clients=5,  # Wait until all 10 clients are available\n",
    ")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Simulate!"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 86,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO flwr 2023-04-30 00:06:50,752 | app.py:146 | Starting Flower simulation, config: ServerConfig(num_rounds=5, round_timeout=None)\n",
      "2023-04-30 00:06:54,990\tINFO worker.py:1625 -- Started a local Ray instance.\n",
      "INFO flwr 2023-04-30 00:06:57,637 | app.py:180 | Flower VCE: Ray initialized with resources: {'object_store_memory': 16786692096.0, 'memory': 33573384192.0, 'GPU': 1.0, 'CPU': 24.0, 'node:127.0.0.1': 1.0}\n",
      "INFO flwr 2023-04-30 00:06:57,638 | server.py:86 | Initializing global parameters\n",
      "INFO flwr 2023-04-30 00:06:57,638 | server.py:273 | Requesting initial parameters from one random client\n",
      "INFO flwr 2023-04-30 00:06:58,305 | server.py:277 | Received initial parameters from one random client\n",
      "INFO flwr 2023-04-30 00:06:58,305 | server.py:88 | Evaluating initial parameters\n",
      "INFO flwr 2023-04-30 00:06:58,306 | server.py:101 | FL starting\n",
      "DEBUG flwr 2023-04-30 00:06:58,306 | server.py:218 | fit_round 1: strategy sampled 5 clients (out of 5)\n",
      "ERROR flwr 2023-04-30 00:06:58,328 | ray_client_proxy.py:87 | \u001b[36mray::launch_and_fit()\u001b[39m (pid=15524, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 148, in launch_and_fit\n",
      "    return maybe_call_fit(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 184, in maybe_call_fit\n",
      "    return client.fit(fit_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 297, in _fit\n",
      "    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 16, in fit\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "ERROR flwr 2023-04-30 00:06:59,057 | ray_client_proxy.py:87 | \u001b[36mray::launch_and_fit()\u001b[39m (pid=16056, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 148, in launch_and_fit\n",
      "    return maybe_call_fit(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 184, in maybe_call_fit\n",
      "    return client.fit(fit_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 297, in _fit\n",
      "    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 16, in fit\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "ERROR flwr 2023-04-30 00:06:59,070 | ray_client_proxy.py:87 | \u001b[36mray::launch_and_fit()\u001b[39m (pid=29428, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 148, in launch_and_fit\n",
      "    return maybe_call_fit(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 184, in maybe_call_fit\n",
      "    return client.fit(fit_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 297, in _fit\n",
      "    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 16, in fit\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "ERROR flwr 2023-04-30 00:06:59,073 | ray_client_proxy.py:87 | \u001b[36mray::launch_and_fit()\u001b[39m (pid=2816, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 148, in launch_and_fit\n",
      "    return maybe_call_fit(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 184, in maybe_call_fit\n",
      "    return client.fit(fit_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 297, in _fit\n",
      "    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 16, in fit\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "ERROR flwr 2023-04-30 00:06:59,078 | ray_client_proxy.py:87 | \u001b[36mray::launch_and_fit()\u001b[39m (pid=26740, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 148, in launch_and_fit\n",
      "    return maybe_call_fit(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 184, in maybe_call_fit\n",
      "    return client.fit(fit_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 297, in _fit\n",
      "    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 16, in fit\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "DEBUG flwr 2023-04-30 00:06:59,081 | server.py:232 | fit_round 1 received 0 results and 5 failures\n",
      "DEBUG flwr 2023-04-30 00:06:59,081 | server.py:168 | evaluate_round 1: strategy sampled 2 clients (out of 5)\n",
      "ERROR flwr 2023-04-30 00:06:59,093 | ray_client_proxy.py:104 | \u001b[36mray::launch_and_evaluate()\u001b[39m (pid=26740, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 160, in launch_and_evaluate\n",
      "    return maybe_call_evaluate(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 205, in maybe_call_evaluate\n",
      "    return client.evaluate(evaluate_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 321, in _evaluate\n",
      "    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 25, in evaluate\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "ERROR flwr 2023-04-30 00:06:59,094 | ray_client_proxy.py:104 | \u001b[36mray::launch_and_evaluate()\u001b[39m (pid=2816, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 160, in launch_and_evaluate\n",
      "    return maybe_call_evaluate(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 205, in maybe_call_evaluate\n",
      "    return client.evaluate(evaluate_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 321, in _evaluate\n",
      "    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 25, in evaluate\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "DEBUG flwr 2023-04-30 00:06:59,098 | server.py:182 | evaluate_round 1 received 0 results and 2 failures\n",
      "DEBUG flwr 2023-04-30 00:06:59,098 | server.py:218 | fit_round 2: strategy sampled 5 clients (out of 5)\n",
      "ERROR flwr 2023-04-30 00:06:59,111 | ray_client_proxy.py:87 | \u001b[36mray::launch_and_fit()\u001b[39m (pid=2816, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 148, in launch_and_fit\n",
      "    return maybe_call_fit(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 184, in maybe_call_fit\n",
      "    return client.fit(fit_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 297, in _fit\n",
      "    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 16, in fit\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "ERROR flwr 2023-04-30 00:06:59,113 | ray_client_proxy.py:87 | \u001b[36mray::launch_and_fit()\u001b[39m (pid=26740, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 148, in launch_and_fit\n",
      "    return maybe_call_fit(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 184, in maybe_call_fit\n",
      "    return client.fit(fit_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 297, in _fit\n",
      "    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 16, in fit\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "ERROR flwr 2023-04-30 00:06:59,117 | ray_client_proxy.py:87 | \u001b[36mray::launch_and_fit()\u001b[39m (pid=29428, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 148, in launch_and_fit\n",
      "    return maybe_call_fit(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 184, in maybe_call_fit\n",
      "    return client.fit(fit_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 297, in _fit\n",
      "    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 16, in fit\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "ERROR flwr 2023-04-30 00:06:59,117 | ray_client_proxy.py:87 | \u001b[36mray::launch_and_fit()\u001b[39m (pid=16056, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 148, in launch_and_fit\n",
      "    return maybe_call_fit(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 184, in maybe_call_fit\n",
      "    return client.fit(fit_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 297, in _fit\n",
      "    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 16, in fit\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "ERROR flwr 2023-04-30 00:06:59,118 | ray_client_proxy.py:87 | \u001b[36mray::launch_and_fit()\u001b[39m (pid=15524, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 148, in launch_and_fit\n",
      "    return maybe_call_fit(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 184, in maybe_call_fit\n",
      "    return client.fit(fit_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 297, in _fit\n",
      "    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 16, in fit\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "DEBUG flwr 2023-04-30 00:06:59,126 | server.py:232 | fit_round 2 received 0 results and 5 failures\n",
      "DEBUG flwr 2023-04-30 00:06:59,127 | server.py:168 | evaluate_round 2: strategy sampled 2 clients (out of 5)\n",
      "ERROR flwr 2023-04-30 00:06:59,138 | ray_client_proxy.py:104 | \u001b[36mray::launch_and_evaluate()\u001b[39m (pid=15524, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 160, in launch_and_evaluate\n",
      "    return maybe_call_evaluate(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 205, in maybe_call_evaluate\n",
      "    return client.evaluate(evaluate_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 321, in _evaluate\n",
      "    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 25, in evaluate\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "ERROR flwr 2023-04-30 00:06:59,139 | ray_client_proxy.py:104 | \u001b[36mray::launch_and_evaluate()\u001b[39m (pid=16056, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 160, in launch_and_evaluate\n",
      "    return maybe_call_evaluate(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 205, in maybe_call_evaluate\n",
      "    return client.evaluate(evaluate_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 321, in _evaluate\n",
      "    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 25, in evaluate\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "DEBUG flwr 2023-04-30 00:06:59,143 | server.py:182 | evaluate_round 2 received 0 results and 2 failures\n",
      "DEBUG flwr 2023-04-30 00:06:59,144 | server.py:218 | fit_round 3: strategy sampled 5 clients (out of 5)\n",
      "ERROR flwr 2023-04-30 00:06:59,154 | ray_client_proxy.py:87 | \u001b[36mray::launch_and_fit()\u001b[39m (pid=16056, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 148, in launch_and_fit\n",
      "    return maybe_call_fit(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 184, in maybe_call_fit\n",
      "    return client.fit(fit_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 297, in _fit\n",
      "    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 16, in fit\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "ERROR flwr 2023-04-30 00:06:59,157 | ray_client_proxy.py:87 | \u001b[36mray::launch_and_fit()\u001b[39m (pid=15524, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 148, in launch_and_fit\n",
      "    return maybe_call_fit(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 184, in maybe_call_fit\n",
      "    return client.fit(fit_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 297, in _fit\n",
      "    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 16, in fit\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "ERROR flwr 2023-04-30 00:06:59,159 | ray_client_proxy.py:87 | \u001b[36mray::launch_and_fit()\u001b[39m (pid=29428, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 148, in launch_and_fit\n",
      "    return maybe_call_fit(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 184, in maybe_call_fit\n",
      "    return client.fit(fit_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 297, in _fit\n",
      "    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 16, in fit\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "ERROR flwr 2023-04-30 00:06:59,160 | ray_client_proxy.py:87 | \u001b[36mray::launch_and_fit()\u001b[39m (pid=16056, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 148, in launch_and_fit\n",
      "    return maybe_call_fit(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 184, in maybe_call_fit\n",
      "    return client.fit(fit_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 297, in _fit\n",
      "    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 16, in fit\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "ERROR flwr 2023-04-30 00:06:59,161 | ray_client_proxy.py:87 | \u001b[36mray::launch_and_fit()\u001b[39m (pid=26740, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 148, in launch_and_fit\n",
      "    return maybe_call_fit(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 184, in maybe_call_fit\n",
      "    return client.fit(fit_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 297, in _fit\n",
      "    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 16, in fit\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "DEBUG flwr 2023-04-30 00:06:59,168 | server.py:232 | fit_round 3 received 0 results and 5 failures\n",
      "DEBUG flwr 2023-04-30 00:06:59,169 | server.py:168 | evaluate_round 3: strategy sampled 2 clients (out of 5)\n",
      "ERROR flwr 2023-04-30 00:06:59,179 | ray_client_proxy.py:104 | \u001b[36mray::launch_and_evaluate()\u001b[39m (pid=16056, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 160, in launch_and_evaluate\n",
      "    return maybe_call_evaluate(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 205, in maybe_call_evaluate\n",
      "    return client.evaluate(evaluate_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 321, in _evaluate\n",
      "    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 25, in evaluate\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "ERROR flwr 2023-04-30 00:06:59,181 | ray_client_proxy.py:104 | \u001b[36mray::launch_and_evaluate()\u001b[39m (pid=26740, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 160, in launch_and_evaluate\n",
      "    return maybe_call_evaluate(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 205, in maybe_call_evaluate\n",
      "    return client.evaluate(evaluate_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 321, in _evaluate\n",
      "    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 25, in evaluate\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "DEBUG flwr 2023-04-30 00:06:59,184 | server.py:182 | evaluate_round 3 received 0 results and 2 failures\n",
      "DEBUG flwr 2023-04-30 00:06:59,186 | server.py:218 | fit_round 4: strategy sampled 5 clients (out of 5)\n",
      "ERROR flwr 2023-04-30 00:06:59,200 | ray_client_proxy.py:87 | \u001b[36mray::launch_and_fit()\u001b[39m (pid=26740, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 148, in launch_and_fit\n",
      "    return maybe_call_fit(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 184, in maybe_call_fit\n",
      "    return client.fit(fit_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 297, in _fit\n",
      "    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 16, in fit\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "ERROR flwr 2023-04-30 00:06:59,202 | ray_client_proxy.py:87 | \u001b[36mray::launch_and_fit()\u001b[39m (pid=29428, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 148, in launch_and_fit\n",
      "    return maybe_call_fit(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 184, in maybe_call_fit\n",
      "    return client.fit(fit_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 297, in _fit\n",
      "    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 16, in fit\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "ERROR flwr 2023-04-30 00:06:59,202 | ray_client_proxy.py:87 | \u001b[36mray::launch_and_fit()\u001b[39m (pid=16056, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 148, in launch_and_fit\n",
      "    return maybe_call_fit(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 184, in maybe_call_fit\n",
      "    return client.fit(fit_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 297, in _fit\n",
      "    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 16, in fit\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "ERROR flwr 2023-04-30 00:06:59,203 | ray_client_proxy.py:87 | \u001b[36mray::launch_and_fit()\u001b[39m (pid=15524, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 148, in launch_and_fit\n",
      "    return maybe_call_fit(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 184, in maybe_call_fit\n",
      "    return client.fit(fit_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 297, in _fit\n",
      "    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 16, in fit\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "ERROR flwr 2023-04-30 00:06:59,205 | ray_client_proxy.py:87 | \u001b[36mray::launch_and_fit()\u001b[39m (pid=2816, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 148, in launch_and_fit\n",
      "    return maybe_call_fit(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 184, in maybe_call_fit\n",
      "    return client.fit(fit_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 297, in _fit\n",
      "    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 16, in fit\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "DEBUG flwr 2023-04-30 00:06:59,212 | server.py:232 | fit_round 4 received 0 results and 5 failures\n",
      "DEBUG flwr 2023-04-30 00:06:59,213 | server.py:168 | evaluate_round 4: strategy sampled 2 clients (out of 5)\n",
      "ERROR flwr 2023-04-30 00:06:59,224 | ray_client_proxy.py:104 | \u001b[36mray::launch_and_evaluate()\u001b[39m (pid=15524, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 160, in launch_and_evaluate\n",
      "    return maybe_call_evaluate(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 205, in maybe_call_evaluate\n",
      "    return client.evaluate(evaluate_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 321, in _evaluate\n",
      "    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 25, in evaluate\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "ERROR flwr 2023-04-30 00:06:59,226 | ray_client_proxy.py:104 | \u001b[36mray::launch_and_evaluate()\u001b[39m (pid=2816, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 160, in launch_and_evaluate\n",
      "    return maybe_call_evaluate(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 205, in maybe_call_evaluate\n",
      "    return client.evaluate(evaluate_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 321, in _evaluate\n",
      "    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 25, in evaluate\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "DEBUG flwr 2023-04-30 00:06:59,231 | server.py:182 | evaluate_round 4 received 0 results and 2 failures\n",
      "DEBUG flwr 2023-04-30 00:06:59,231 | server.py:218 | fit_round 5: strategy sampled 5 clients (out of 5)\n",
      "ERROR flwr 2023-04-30 00:06:59,243 | ray_client_proxy.py:87 | \u001b[36mray::launch_and_fit()\u001b[39m (pid=15524, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 148, in launch_and_fit\n",
      "    return maybe_call_fit(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 184, in maybe_call_fit\n",
      "    return client.fit(fit_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 297, in _fit\n",
      "    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 16, in fit\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "ERROR flwr 2023-04-30 00:06:59,245 | ray_client_proxy.py:87 | \u001b[36mray::launch_and_fit()\u001b[39m (pid=2816, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 148, in launch_and_fit\n",
      "    return maybe_call_fit(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 184, in maybe_call_fit\n",
      "    return client.fit(fit_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 297, in _fit\n",
      "    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 16, in fit\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "ERROR flwr 2023-04-30 00:06:59,248 | ray_client_proxy.py:87 | \u001b[36mray::launch_and_fit()\u001b[39m (pid=16056, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 148, in launch_and_fit\n",
      "    return maybe_call_fit(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 184, in maybe_call_fit\n",
      "    return client.fit(fit_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 297, in _fit\n",
      "    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 16, in fit\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "ERROR flwr 2023-04-30 00:06:59,248 | ray_client_proxy.py:87 | \u001b[36mray::launch_and_fit()\u001b[39m (pid=29428, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 148, in launch_and_fit\n",
      "    return maybe_call_fit(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 184, in maybe_call_fit\n",
      "    return client.fit(fit_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 297, in _fit\n",
      "    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 16, in fit\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "ERROR flwr 2023-04-30 00:06:59,249 | ray_client_proxy.py:87 | \u001b[36mray::launch_and_fit()\u001b[39m (pid=2816, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 148, in launch_and_fit\n",
      "    return maybe_call_fit(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 184, in maybe_call_fit\n",
      "    return client.fit(fit_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 297, in _fit\n",
      "    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 16, in fit\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "DEBUG flwr 2023-04-30 00:06:59,257 | server.py:232 | fit_round 5 received 0 results and 5 failures\n",
      "DEBUG flwr 2023-04-30 00:06:59,258 | server.py:168 | evaluate_round 5: strategy sampled 2 clients (out of 5)\n",
      "ERROR flwr 2023-04-30 00:06:59,268 | ray_client_proxy.py:104 | \u001b[36mray::launch_and_evaluate()\u001b[39m (pid=2816, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 160, in launch_and_evaluate\n",
      "    return maybe_call_evaluate(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 205, in maybe_call_evaluate\n",
      "    return client.evaluate(evaluate_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 321, in _evaluate\n",
      "    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 25, in evaluate\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "ERROR flwr 2023-04-30 00:06:59,270 | ray_client_proxy.py:104 | \u001b[36mray::launch_and_evaluate()\u001b[39m (pid=29428, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 877, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 881, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_client_proxy.py\", line 160, in launch_and_evaluate\n",
      "    return maybe_call_evaluate(\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\client.py\", line 205, in maybe_call_evaluate\n",
      "    return client.evaluate(evaluate_ins)\n",
      "  File \"c:\\Users\\gamin\\anaconda3\\envs\\fed_learn\\lib\\site-packages\\flwr\\client\\app.py\", line 321, in _evaluate\n",
      "    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2546506652.py\", line 25, in evaluate\n",
      "  File \"C:\\Users\\gamin\\AppData\\Local\\Temp\\ipykernel_23968\\2549093744.py\", line 19, in set_model_params\n",
      "TypeError: list indices must be integers or slices, not str\n",
      "DEBUG flwr 2023-04-30 00:06:59,274 | server.py:182 | evaluate_round 5 received 0 results and 2 failures\n",
      "INFO flwr 2023-04-30 00:06:59,275 | server.py:147 | FL finished in 0.9685194999999567\n",
      "INFO flwr 2023-04-30 00:06:59,276 | app.py:218 | app_fit: losses_distributed []\n",
      "INFO flwr 2023-04-30 00:06:59,277 | app.py:219 | app_fit: metrics_distributed_fit {}\n",
      "INFO flwr 2023-04-30 00:06:59,277 | app.py:220 | app_fit: metrics_distributed {}\n",
      "INFO flwr 2023-04-30 00:06:59,278 | app.py:221 | app_fit: losses_centralized []\n",
      "INFO flwr 2023-04-30 00:06:59,279 | app.py:222 | app_fit: metrics_centralized {}\n"
     ]
    },
    {
     "data": {
      "text/plain": []
     },
     "execution_count": 86,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\n",
    "fl.simulation.start_simulation(\n",
    "    client_fn=launch_client,\n",
    "    num_clients=5,\n",
    "    config=fl.server.ServerConfig(num_rounds=5),\n",
    "    strategy=strategy,\n",
    "    client_resources=None,\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "fed_learn",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.16"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
